### ISSUE TITLE
What's the default routes for all route codes?

### ISSUE THREAD

**Issue by zhaoyao91** [meteor-useraccounts/flow-routing#10]
I didn't find the answer in the readme. did I miss something?

**Comment by jshimko** [comment]
See the chart of defaults in the iron-routing package.  They should all be the same.

https://github.com/meteor-useraccounts/iron-routing#routes

**Comment by zhaoyao91** [comment]
@jshimko thanks. I think there should be a copy or link to that chart in this doc to reduce the usage confusion.

**Comment by jshimko** [comment]
Done.  :)
https://github.com/meteor-useraccounts/flow-routing/pull/11
