### ISSUE TITLE
Router jumps to home page if login dialog is used in a modal

### ISSUE THREAD

**Issue by derwaldgeist** [meteor-useraccounts/flow-routing#12]
I am using the approach of @maxhodges to use the login dialog in a modal dialog, like explained here:
https://github.com/meteor-useraccounts/bootstrap/issues/25

Yet, every time the user logs in, flow router automatically jumps to the home page of my application instead of staying on the current page. It does not behave this way if I am using the standard full-page login dialog, so my flow router configuration seems to be correct and it must have something to do with the useraccounts package itself (either core or flowrouting).

**Comment by Maxhodges** [comment]
i think you can set that

see 
"homeRoutePath" in le guide

https://github.com/meteor-useraccounts/core/blob/master/Guide.md

**Comment by splendido** [comment]
For `useraccounts:iron-routing` it's enough to set `AccountsTemplates.avoidRedirect` to `true` to solve this issue: see [this line](https://github.com/meteor-useraccounts/iron-routing/blob/master/lib/client.js#L135)

At the moment that's not the same for `useraccounts:flow-routing`: see [this line](https://github.com/meteor-useraccounts/flow-routing/blob/master/lib/client/client.js#L96)
I see there's an `avoidDefaultRefirect` [here](https://github.com/meteor-useraccounts/flow-routing/blob/master/lib/client/client.js#L63) and [here](https://github.com/meteor-useraccounts/flow-routing/blob/master/lib/client/client.js#L127-L128) but actually it's never initialized...

@jshimko do you have any memory about this change we had during the split of routing stuff?

Should we rename `avoidDefaultRedirect` back to `avoidRedirect` (which is initialized [here](https://github.com/meteor-useraccounts/core/blob/master/lib/client.js#L31) btw...) and modify the [link click](https://github.com/meteor-useraccounts/flow-routing/blob/master/lib/client/client.js#L91-L94) to be alike [the one](https://github.com/meteor-useraccounts/iron-routing/blob/master/lib/client.js#L130-L137) we have for IR?

**Comment by derwaldgeist** [comment]
Thanks for taking action on this, highly appreciated!

**Comment by jshimko** [comment]
@splendido @derwaldgeist  Yeah, I guess that one just flew under the radar when we were making the conversion.  I'll take a closer look and see if I can get it sorted out.

**Comment by derwaldgeist** [comment]
Thanks for picking this up!

**Comment by splendido** [comment]
This should be solved now, thanks @jshimko!

**Comment by derwaldgeist** [comment]
Oh, great, will have a look at it! Thanks.
