### ISSUE TITLE
Setting homeRoutePath has no effect?

### ISSUE THREAD

**Issue by madhan5000** [meteor-useraccounts/flow-routing#14]
Hello authors,
it looks like homeRoutePath has no effect? I want to redirect after sign-in. It gets redirected back to '/' route.

here is my config. I using Meteor 1.2

    AccountsTemplates.configure({
    defaultLayout: 'appLayout',
	  defaultLayoutRegions: {
      header : "header",
      footer: "footer"
    },
    defaultContentRegion: 'area',

    showForgotPasswordLink: true,
    overrideLoginErrors: true,
    enablePasswordChange: true,
    sendVerificationEmail: false,

    //enforceEmailVerification: true,
    //confirmPassword: true,
    //continuousValidation: false,
    //displayFormLabels: true,
    forbidClientAccountCreation: true,
    //formValidationFeedback: true,
    homeRoutePath: '/plans', //<-- has no effect
    //showAddRemoveServices: false,
    //showPlaceholders: true,

    negativeValidation: true,
    positiveValidation:true,
    negativeFeedback: false,
    positiveFeedback:false,

    // Privacy Policy and Terms of Use
    //privacyUrl: 'privacy',
    //termsUrl: 'terms-of-use',

});

my route

     FlowRouter.route('/plans', {
     triggersEnter: [AccountsTemplates.ensureSignedIn],
     action: function(params) {
         BlazeLayout.render("appLayout", {area: "plans"});
     }    });
Thanks for your help!

Code in Question : 
https://github.com/meteor-useraccounts/flow-routing/blob/master/lib/client/client.js#L142

the line above fails with my configuration.

**Comment by splendido** [comment]
You're right!
It seems that the previous path always take precedence and the execution passes through [this line](https://github.com/meteor-useraccounts/flow-routing/blob/master/lib/client/client.js#L142) even when you configure `homeRoutePath`.

I'll have a better look at this asap.

**Comment by splendido** [comment]
@madhan5000 I've had a better look at this.

The only case where `homeRoutePath` gets used is when you directly head to, e.g. `http://your.app/signIn` and your old session is resumed (i.e. you're already logged in...).
In this case there's no `previousPath` and the client is redirected to `homeRoutePath`.

In case you're trying to force a redirect after a regular sign in, you can set the `redirect` field while configuring the `signIn` route:

```javascript
AccountsTemplates.configureRoute(`signIn`, {
  redirect: `routeName or route path of function`
});
```

In any case the documentation needs to be corrected.
Also the `redirect` option for routes should be documented for `AccountsTemplates.configureRoute` in the `flow-routing` package which is currently missing.
See [here](https://github.com/meteor-useraccounts/flow-routing/blob/2d98f3cf82a2d676809e3e6bba3e90f48b1e07f3/lib/client/client.js#L133) for the relevant code and [here](https://github.com/meteor-useraccounts/iron-routing#routes) for the corresponding section for the `iron-routing`.

cc: @jshimko

**Comment by splendido** [comment]
@madhan5000 `AccountsTemplates.ensureSignedIn` in any case should redirect you back to your `/plans` route after a successful login...

**Comment by madhan5000** [comment]
@splendido Thanks for getting back to me. Yes, I agree clear documentation would definitely help for those who don't have any iron-router experience. Thanks again.

**Comment by madhan5000** [comment]
@NitroBAY I am not the original author or a contributor. Please contact @splendido
