### ISSUE TITLE
'resetPwd' not adding route '/reset-password'.

### ISSUE THREAD

**Issue by shwaydogg** [meteor-useraccounts/flow-routing#18]
I've added `AccountsTemplates.configureRoute('resetPwd');`, but '/reset-password' route is still not found. 

I was able successfully add `AccountsTemplates.configureRoute('signIn');` and `AccountsTemplates.configureRoute('changePwd');` successfully the same way.  I'm not sure what the issue is.

**Comment by splendido** [comment]
@shwaydogg [here](https://github.com/meteor-useraccounts/flow-routing/blob/master/lib/core.js#L157) is where the `:paramToken` parameter is added to the route...
Where you able to get things working without tweaks?

**Comment by splendido** [comment]
@shwaydogg please also make sure you call `AccountsTemplates.configureRoute('resetPwd');` on both the client and server sides.
