### ISSUE TITLE
Is there a demo repo for flow routing with React somewhere?

### ISSUE THREAD

**Issue by elie222** [meteor-useraccounts/flow-routing#21]
I just get a blank page when I go to the sign in route even though it's configured.

**Comment by jshimko** [comment]
Sorry, forgot to respond here after I put the boilerplate together...

You can find an example app using `useraccounts:flow-routing` with React here:

https://github.com/meteor-useraccounts/boilerplates/tree/master/bootstrap-flow-router-react

Also note the updated [readme](https://github.com/meteor-useraccounts/flow-routing) for this repo.  I added a few more details about React usage (which are all demonstrated in the example repo as well)

**Comment by elie222** [comment]
Thanks!
