### ISSUE TITLE
configured routes redirect to main page

### ISSUE THREAD

**Issue by avalanche1** [meteor-useraccounts/flow-routing#24]
I use most basic setup: `AccountsTemplates.configureRoute('signIn');` and when I go to `/sign-in` it just redirects to `/`. What could be wrong?

**Comment by jshimko** [comment]
Are you already signed in maybe?  :)

If you are, that's the expected behavior.

**Comment by splendido** [comment]
I confirm this is the expected behavior when you got to a `signIn` page being already logged in.
