### ISSUE TITLE
Usage Question: Verify Email

### ISSUE THREAD

**Issue by GerhardJO** [meteor-useraccounts/flow-routing#39]
Hello,

Thanks for this awesome meteor package. I was able to configure my app to send a verification email and was able to send the mail using my Mailgun sandbox domain.

The verification link I receive looks as follows http://localhost:3000/#/verify-email/<verify token>
Clicking this link just takes the user to the Home route.

Does flow-routing handle the verification callback or should I implement it myself?

Thanks

**Comment by nicooprat** [comment]
Same problem here, no clue how to do :(

**Comment by GerhardJO** [comment]
Hi @nicooprat 

Thanks for reminding me to look into this again. The answer is indeed to implement the verification callback as described in:
[http://docs.meteor.com/api/passwords.html#Accounts-onEmailVerificationLink](http://docs.meteor.com/api/passwords.html#Accounts-onEmailVerificationLink)
and in the callback calling:
[http://docs.meteor.com/api/passwords.html#Accounts-verifyEmail](http://docs.meteor.com/api/passwords.html#Accounts-verifyEmail)

I'm assuming without testing that this will be the same for all the Accounts-Password callbacks.

Implement the code below in client code but not in client.startup as per the docs.

```javascript
Accounts.onEmailVerificationLink(function(token){
  console.log(token);
  Accounts.verifyEmail(token, function(Error){
     if(Error){
       console.log(Error);
     }
  });
});
```

Cheers

**Comment by nicooprat** [comment]
Right, thanks! I'll add that **the route override must be accessible in client and server side**.
