### ISSUE TITLE
Ensure sign in exception

### ISSUE THREAD

**Issue by shactdeveloper** [meteor-useraccounts/flow-routing#9]
Hi! I have all my routes protected with this
FlowRouter.triggers.enter([AccountsTemplates.ensureSignedIn]);

But how can i make an exception?
I want to make the path /freeforall not protected
How can I do this ?

**Comment by jshimko** [comment]
```js
// assuming the route name is "freeforall"
FlowRouter.triggers.enter([AccountsTemplates.ensureSignedIn], { except: ["freeforall"] });
```
https://github.com/kadirahq/flow-router/#defining-triggers-globally

**Comment by shactdeveloper** [comment]
Nice! thanks! is there a way to define an exception for an entire group ?

**Comment by jshimko** [comment]
https://github.com/kadirahq/flow-router/#group-routes

**Comment by jshimko** [comment]
Using their example...

```js
var adminRoutes = FlowRouter.group({
  prefix: '/admin',
  name: 'admin',
  triggersEnter: [AccountsTemplates.ensureSignedIn]
});
```

**Comment by splendido** [comment]
@shactdeveloper, is this solved?

**Comment by shactdeveloper** [comment]
Yes, thank you so much my friends!

**Comment by splendido** [comment]
you're welcome!
